# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1681e13781861b8c2b06c00f98f255679187ecbc1a213b42ef114fbce77c4cd80f03ac8b6008f12303dad14179ec4ab580f86227884043408de6044f6b6f04d8

test:
  secret_key_base: fe828933095de0e3745f36e176b81dce9bf3a541370de52c1b3d073ccfafa56878485beffa9fe06f5c67730f5ae967aa0ae97c9b008e9929b4ee427393dc5b9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["PRODUCTION_SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["STAGING_SECRET_KEY_BASE"] %>

secret_key_base: fe828933095de0e3745f36e176b81dce9bf3a541370de52c1b3d073ccfafa56878485beffa9fe06f5c67730f5ae967aa0ae97c9b008e9929b4ee427393dc5b9d
